module.exports = [{
 title: "密码认证",
 meta: "",
 index: ["/auth", "/auth.html"],
 path: "htmls/auth.html",
}, {
 nav: true,
 title: "首页",
 meta: "",
 index: ["/", "/index.html"],
 path: "htmls/index.html",
 showHeader: true,
 showFooter: true,
 // showType: true,
 // showTag: true,
}, {
 nav: true,
 title: "专题",
 meta: "",
 index: ["/types", "/types.html"],
 path: "htmls/types.html",
 showHeader: true,
 showFooter: true,
 content: "types",
}, {
 title: "标签",
 meta: "",
 index: ["/tags", "/tags.html"],
 path: "htmls/tags.html",
 showHeader: true,
 showFooter: true,
 content: "tags",
}, {
 nav: true,
 title: "归档",
 meta: "",
 index: ["/timeline", "/timeline.html"],
 path: "htmls/timeline.html",
 showHeader: true,
 showFooter: true,
 content: "timeline"
}, {
 nav: true,
 title: "关于",
 meta: "",
 index: ["/about", "/about.html"],
 path: "htmls/about.html",
 showHeader: true,
 showFooter: true,
}, {
 title: "分类",
 meta: "",
 index: ["/type-index", "/type-index.html"],
 path: "htmls/type-index.html",
 showHeader: true,
 showFooter: true,
}, {
 title: "标签",
 meta: "",
 index: ["/tag-index", "/tag-index.html"],
 path: "htmls/tag-index.html",
 showHeader: true,
 showFooter: true,
}, {
 title: "详情页",
 meta: "",
 index: ["/artical-detail", "/artical-detail.html"],
 path: "htmls/artical-detail.html",
 showHeader: true,
 showFooter: true,
 showType: true,
 showTag: true,
 content: "md",
}]